#!/usr/bin/env zsh
set -eu

backup_and_link() {
  local source=$1
  local target=$2
  local __dry_run="${DRYRUN+echo dryrun-would-exec:}"

  if [[ -L ${target} || -f ${target} || -d ${target} ]]; then
    # If already a symlink to desired source, we're done.
    [[ -L ${target} && $(readlink "${target}") == "${source}" ]] && return

    datestamp=${datestamp:-$(date -u +%Y%m%dT%H%M%SZ)}  # cached
    local backup="${target}.bak.${datestamp}"
    echo "Old ${target} backed up as ${backup}" >&2
    ${__dry_run} mv "${target}" "${backup}"
  fi

  ${__dry_run} ln -s "${source}" "${target}"
}

HERE=${0:a:h}  # equilvalent to $(dirname $(realpath $0))
backup_and_link "${HERE}/zshrc" "${HOME}/.zshrc"
